@startuml Transaction
'"Transaction" class functionality
skinparam defaultTextAlignment center
start
partition "constructor(self, amount, type)" {
  :Create Transaction object with amount and type string;
}
stop
@enduml

@startuml BankAccount
'"BankAccount" class functionality
skinparam defaultTextAlignment center
start
partition "constructor(self, number, owner, balance)" {
    :Create BankAccount object with account number,
    owner, balance, and empty list transactions;
}
repeat :wait for method call;
  split
  partition "deposit(self, amount)" {
    :Add amount to balance;
    :Add new Transaction(amount, "Deposit")
    to transactions;
  }
  split again
  partition "withdraw(self, amount)" {
    if (balance >= amount) then (yes)
      :Subtract amount from balance;
      :Add new Transaction(amount, "Withdrawal")
      to transactions;
    else (no)
      :Return "Insufficient Funds";
    endif
  }
  end split
repeat while (object exists?) is (yes)
->no;
stop
@enduml

@startuml Customer
'"Customer" class functionality
skinparam defaultTextAlignment center
start
partition "constructor(self, name, account)" {
  :Create Customer object with name 
  and BankAccount account;
}
stop
@enduml

@startuml Bank
'"Bank" class functionality
skinparam defaultTextAlignment center
start
partition "constructor(self)" {
  :Create Bank object with 
  empty list customers;
}
repeat :wait for method call;
  split
  partition "add_customer(self, customer)" {
    :Add given Customer to customers;
  }
  split again
  partition "remove_customer(self, customer)" {
    :Remove given Customer from customers;
  }
  end split
repeat while (object exists?) is (yes)
->no;
stop
@enduml